spring:
  application:
    name: PixelHub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/data?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true"
    username: root
    password: FunWorld
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  pattern:
    console: "[%d{yyyy-MM-dd hh:mm:ss}] [%thread/%clr(%level)] [%clr(%logger{0}){blue}]: %msg%n"
