# PixelHub Config #

database: # 数据库名默认为datas 使用user表
  username: root # 用户名
  password: FunWorld # 密码

repository:
  root: ./repos # 仓库根目录

server:
  port: 8080 # web / git 端口
  ip: localhost # 必填: 用于URL跳转等

admin: #管理员账户 (不建议用此账户递交代码)
  username: Administrator
  email: admin@pixel.com
  password: pixel114514